"use client";
// import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";
import Header from "./component/Header";
import { createTheme } from "@mui/material";
import { useState } from "react";
import { ThemeProvider } from "@emotion/react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [themeMode, setThemeMode] = useState("light");
  const theme = createTheme({
    breakpoints: {
      values: {
        xs: 0,
        sm: 700,
        md: 1000,
      },
      palette: {
        mode: themeMode,
        primary: {
          light: "#757ce8",
          main: "#3f50b5",
          dark: "#002884",
          contrastText: "#fff",
        },
        secondary: {
          light: "#ff7961",
          main: "#f44336",
          dark: "#ba000d",
          contrastText: "#000",
        },
      },
    },
  });
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
